-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "userId" DROP NOT NULL;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerName" VARCHAR(100);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerEmail" VARCHAR(254);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "customerPhone" VARCHAR(20);
