import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import path from 'node:path';
const require=createRequire('D:/PBL4-517/website/frontend/package.json');
const {chromium}=require('playwright');
const out=process.argv[2],base='https://47.129.214.70';
const browser=await chromium.launch({headless:true});
const c=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const page=await c.newPage();
await c.route('**/api/**',route=>route.request().method()==='GET'?route.continue():route.abort());
const result={checks:[]};
await page.goto(base+'/products?search=not-found-audit-517',{waitUntil:'networkidle'});
await page.getByRole('heading',{name:'Không tìm thấy sản phẩm phù hợp'}).waitFor();
await page.getByRole('searchbox').fill('chuột');
await page.getByRole('button',{name:'Xóa tất cả bộ lọc'}).click();
const immediately=page.url();
await page.waitForTimeout(600);
await page.locator('.product-card').first().waitFor();
result.checks.push({name:'reset-with-pending-debounce',immediately,after:page.url(),input:await page.getByRole('searchbox').inputValue(),cards:await page.locator('.product-card').count()});
await page.goto(base+'/products',{waitUntil:'networkidle'});
await page.locator('.product-card').first().waitFor();
await page.screenshot({path:path.join(out,'catalog-first-screen-390.png')});
await page.setViewportSize({width:1440,height:900});
await page.goto(base+'/products',{waitUntil:'networkidle'});
for(let y=0;y<2500;y+=500){await page.evaluate(y=>scrollTo(0,y),y);await page.waitForTimeout(80);}
await page.waitForLoadState('networkidle');
await page.evaluate(()=>scrollTo(0,0));
await page.screenshot({path:path.join(out,'catalog-loaded-1440.png'),fullPage:true});
await c.close();
await browser.close();
await fs.writeFile(path.join(out,'final-checks.json'),JSON.stringify(result,null,2));
console.log(JSON.stringify(result));
